CREATE TABLE IF NOT EXISTS `storageitems` (
  `userid` int(11) NOT NULL,
  `world_id` int(11) NOT NULL,
  `slot` smallint(6) NOT NULL,
  `itemid` int(11) NOT NULL,
  `amount` int(11) NOT NULL default '1',
  `type` tinyint(4) NOT NULL default '0',
  `slots` tinyint(4) NOT NULL default '7',
  `scrolls` tinyint(4) NOT NULL default '0',
  `istr` smallint(6) NOT NULL default '0',
  `idex` smallint(6) NOT NULL default '0',
  `iint` smallint(6) NOT NULL default '0',
  `iluk` smallint(6) NOT NULL default '0',
  `ihp` smallint(6) NOT NULL default '0',
  `imp` smallint(6) NOT NULL default '0',
  `iwatk` smallint(6) NOT NULL default '0',
  `imatk` smallint(6) NOT NULL default '0',
  `iwdef` smallint(6) NOT NULL default '0',
  `imdef` smallint(6) NOT NULL default '0',
  `iacc` smallint(6) NOT NULL default '0',
  `iavo` smallint(6) NOT NULL default '0',
  `ihand` smallint(6) NOT NULL default '0',
  `ispeed` smallint(6) NOT NULL default '0',
  `ijump` smallint(6) NOT NULL default '0',
  PRIMARY KEY  (`userid`,`world_id`,`slot`)
);
