ALTER TABLE characters
	ADD overall_cpos INT(11) UNSIGNED NOT NULL DEFAULT 0,
	ADD overall_opos INT(11) UNSIGNED NOT NULL DEFAULT 0,
	ADD world_cpos INT(11) UNSIGNED NOT NULL DEFAULT 0,
	ADD world_opos INT(11) UNSIGNED NOT NULL DEFAULT 0,
	ADD job_cpos INT(11) UNSIGNED NOT NULL DEFAULT 0,
	ADD job_opos INT(11) UNSIGNED NOT NULL DEFAULT 0,
	ADD fame_cpos INT(11) UNSIGNED NOT NULL DEFAULT 0,
	ADD fame_opos INT(11) UNSIGNED NOT NULL DEFAULT 0
