ALTER TABLE `alliances` CHANGE `notice` `notice` varchar(100) DEFAULT '';
ALTER TABLE `alliances` CHANGE `name` `name` varchar(15);
ALTER TABLE `alliances` CHANGE `worldid` `worldid` tinyint(3);
ALTER TABLE `alliances` CHANGE `rank1title` `rank1title` varchar(10);
ALTER TABLE `alliances` CHANGE `rank2title` `rank2title` varchar(10);
ALTER TABLE `alliances` CHANGE `rank3title` `rank3title` varchar(10);
ALTER TABLE `alliances` CHANGE `rank4title` `rank4title` varchar(10);
ALTER TABLE `alliances` CHANGE `rank5title` `rank5title` varchar(10);
ALTER TABLE `alliances` CHANGE `capacity` `capacity` tinyint(3);
ALTER TABLE `guilds` CHANGE `name` `name` varchar(15);
ALTER TABLE `guilds` CHANGE `world` `worldid` tinyint(3) NOT NULL;
ALTER TABLE `guilds` CHANGE `rank1title` `rank1title` varchar(10);
ALTER TABLE `guilds` CHANGE `rank2title` `rank2title` varchar(10);
ALTER TABLE `guilds` CHANGE `rank3title` `rank3title` varchar(10);
ALTER TABLE `guilds` CHANGE `rank4title` `rank4title` varchar(10);
ALTER TABLE `guilds` CHANGE `rank5title` `rank5title` varchar(10);
ALTER TABLE `guilds` CHANGE `notice` `notice` varchar(100) DEFAULT '';
ALTER TABLE `guilds` CHANGE `alliance` `alliance` int(11);
ALTER TABLE `guilds` CHANGE `capacity` `capacity` tinyint(3);
ALTER TABLE `guilds` CHANGE `logoBG` `logobg` smallint(6);
ALTER TABLE `guilds` CHANGE `logoBGColor` `logobgcolor` tinyint(3) UNSIGNED;
ALTER TABLE `guilds` CHANGE `logo` `logo` smallint(6);
ALTER TABLE `guilds` CHANGE `logoColor` `logocolor` tinyint(3) UNSIGNED;
ALTER TABLE `characters` CHANGE `guild` `guildid` int(11);
ALTER TABLE `characters` CHANGE `alliance` `allianceid` int(11);
ALTER TABLE `guild_bbs_threads` CHANGE `content` `content` varchar(400) DEFAULT '';