ALTER TABLE `guilds` CHANGE `gp` `points` INT(10) UNSIGNED DEFAULT '0' NOT NULL, 
CHANGE `logo` `logo` SMALLINT(6) DEFAULT '0' NULL, 
CHANGE `logocolor` `logocolor` TINYINT(3) UNSIGNED DEFAULT '0' NULL, 
CHANGE `name` `name` VARCHAR(15) NOT NULL, 
CHANGE `capacity` `capacity` TINYINT(3) DEFAULT '10' NULL, 
CHANGE `logobg` `logobg` SMALLINT(6) DEFAULT '0' NULL, 
CHANGE `logobgcolor` `logobgcolor` TINYINT(3) UNSIGNED DEFAULT '0' NULL, 
CHANGE `notice` `notice` VARCHAR(100) DEFAULT '' NULL, 
CHANGE `alliance` `allianceid` INT(11) DEFAULT '0' NULL, 
CHANGE `rank1title` `rank1title` VARCHAR(10) DEFAULT 'Master' NULL, 
CHANGE `rank2title` `rank2title` VARCHAR(10) DEFAULT 'Jr.Master' NULL, 
CHANGE `rank3title` `rank3title` VARCHAR(10) DEFAULT 'Member' NULL,
CHANGE `rank4title` `rank4title` VARCHAR(10) DEFAULT '' NULL, 
CHANGE `rank5title` `rank5title` VARCHAR(10) DEFAULT '' NULL;

ALTER TABLE `alliances` CHANGE `worldid` `worldid` TINYINT(3) UNSIGNED NOT NULL, 
CHANGE `name` `name` VARCHAR(15) NOT NULL, 
CHANGE `notice` `notice` VARCHAR(100) DEFAULT '' NULL, 
CHANGE `rank1title` `rank1title` VARCHAR(10) DEFAULT 'Master' NULL, 
CHANGE `rank2title` `rank2title` VARCHAR(10) DEFAULT 'Jr.Master' NULL, 
CHANGE `rank3title` `rank3title` VARCHAR(10) DEFAULT 'Member' NULL, 
CHANGE `rank4title` `rank4title` VARCHAR(10) DEFAULT '' NULL, 
CHANGE `rank5title` `rank5title` VARCHAR(10) DEFAULT '' NULL, 
CHANGE `capacity` `capacity` TINYINT(3) DEFAULT '2' NULL;
